### ISSUE TITLE
README has outdated usage information

### ISSUE THREAD

**Issue by metrip** [Dean177/jest-to-match-shape-of#38]
README.md states the way to use the matchers is

```
// src/setupTestEnvironment.ts
import 'jest-to-match-shape-of'
```

But this leads to an error:
```
TypeError: expect(...).toMatchShapeOf is not a function
```

The working way of using `expect.extend` is stated in 30a625e32d684a35d51c0b491cd0b96072d7fef3 but changes seem to be lost in master.

**Comment by Dean177** [comment]
Thanks for catching and taking the time to create an issue @metrip, I have updated the Readme to have accurate installation and usage instructions.
