### ISSUE TITLE
Upgrade jest to match create-react-app version

### ISSUE THREAD

**Issue by christian-cuna** [Dean177/jest-to-match-shape-of#80]
`create-react-app@4.0.0` was just released and it has `jest@26.6.0` as devDependency. The current version of `jest-to-match-shape-of` has `jest@25.x` as peerDependency, resulting in an "incorrect peer dependency" warning when used together with the latest version of `create-react-app`.

Assuming it does not break anything, would it be possible to update the peerDependency to something like `jest@26.x` ?

**Comment by Dean177** [comment]
I would love a pull request if you have the time
