### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by gamemaker1** [Dean177/jest-to-match-shape-of#93]
Hi @Dean177,

I'm using this package with Jest 27 in a project - however, the latest released version (1.3.1) requires Jest `v25.x || v26.x` as a peer dependency. This causes npm to abort installation unless I set the `--legacy-peer-deps` option to `true`.

I noticed that this was fixed in 3f59690a1567137f74e0bea62d11a9493c503d1f, however, a new version that includes the commit has not yet been released. Could you please release a new version that includes these changes so we don't need to use the `--legacy-peer-deps` option?

Thanks a lot!

**Comment by Dean177** [comment]
Hey @gamemaker1, I have now published 1.3.2

**Comment by gamemaker1** [comment]
Thanks a lot <3
